---
name: Yaml checks
on: push
jobs: 
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - name: Git check
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint .