name: Yaml checks
on: push
jobs: 
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - name: Git check
        uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        
