name: Validate YAML
on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      file_path: ${{ steps.find_yaml.outputs.file_path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Find a YAML file
        id: find_yaml
        run: |
          file_path=$(find . -name '*.yml' -o -name '*.yaml' | head -n 1)
          echo "YAML file found: $file_path"
          echo "file_path=${file_path}" >> $GITHUB_OUTPUT
          
  validate:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate YAML
        uses: ./.github/actions/yaml-check
        with:
          file_path: ${{ needs.lint.outputs.file_path }}

     
